[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "mol-strudel"
version = "1.0.2"
authors = [
  { name="Luis Bonah", email="bonah@ph1.uni-koeln.de" },
]
description = "STRUcture DEtermination Library for molecular rotational spectroscopy"
readme = "README.md"
requires-python = ">=3.7"
dependencies = ['numpy', 'scipy']
license = "MIT"
classifiers = [
	"Programming Language :: Python :: 3",
	"Operating System :: OS Independent",
]
keywords = ["Structure Determination", "Molecules", "Spectroscopy"]

[project.optional-dependencies]
dev = [
    "ruff",
]

[project.urls]
"Homepage" = "https://github.com/Ltotheois/Strudel/"
